/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.temperatureconverterusingswing;

import com.mycompany.temperatureconverterusingswing.model.Temperature;
import com.mycompany.temperatureconverterusingswing.model.TemperatureUnit;
import com.mycompany.temperatureconverterusingswing.service.TemperatureConversionService;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jayar
 */
public class TemperatureConverterJFrame extends javax.swing.JFrame {
    
    DefaultListModel<TemperatureUnit> tempUnitModel;
    TemperatureConversionService tempConvServ;

    /**
     * Creates new form TemperatureConverterJFrame
     */
    public TemperatureConverterJFrame() {
        initComponents();
        
        tempConvServ = new TemperatureConversionService();
        
        tempUnitModel = new DefaultListModel<>();
        lstTempFrom.setModel(tempUnitModel);
        lstTempTo.setModel(tempUnitModel);
        
        TemperatureUnit[] tempUnits = TemperatureUnit.values();
        for (TemperatureUnit unit : tempUnits) {
            tempUnitModel.addElement(unit);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfldTempFrom = new javax.swing.JTextField();
        txtfldTempTo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTempFrom = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTempTo = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        lbelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("From:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("To:");

        txtfldTempFrom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtfldTempFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfldTempFromKeyReleased(evt);
            }
        });

        txtfldTempTo.setEditable(false);
        txtfldTempTo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lstTempFrom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTempFrom.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTempFrom.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTempFromValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTempFrom);

        lstTempTo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTempTo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTempTo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTempToValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstTempTo);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Result:");

        lbelResult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfldTempFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfldTempTo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfldTempFrom)
                    .addComponent(txtfldTempTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lbelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstTempFromValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTempFromValueChanged
        if (!evt.getValueIsAdjusting()) {
            TemperatureConversion();
        }        
    }//GEN-LAST:event_lstTempFromValueChanged

    private void lstTempToValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTempToValueChanged
        if (!evt.getValueIsAdjusting()) {
            TemperatureConversion();
        }
    }//GEN-LAST:event_lstTempToValueChanged

    private void txtfldTempFromKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfldTempFromKeyReleased
        TemperatureConversion();
    }//GEN-LAST:event_txtfldTempFromKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureConverterJFrame().setVisible(true);
            }
        });
    }
    
    private void TemperatureConversion() {
        TemperatureUnit tempFromUnit = lstTempFrom.getSelectedValue();
        TemperatureUnit tempToUnit = lstTempTo.getSelectedValue();
        String tempFrom = txtfldTempFrom.getText();
        
        
        if (!"".equals(tempFrom)) {
            try {
                double temp = Double.valueOf(tempFrom);

                if (tempFromUnit != null && tempToUnit != null) {
                    if (tempFromUnit == tempToUnit) {
                        lbelResult.setText(temp + " " + tempFromUnit + " = " + temp + " " + tempToUnit);
                        txtfldTempTo.setText(String.valueOf(temp));
                    } else {
                        Temperature tempFr = new Temperature(temp, tempFromUnit);
                        Temperature tempTo = tempConvServ.convert(tempFr, tempToUnit);
                        lbelResult.setText(String.format("%.2f %s = %.2f %s", tempFr.getValue(), tempFromUnit, tempTo.getValue(), tempToUnit));
                        txtfldTempTo.setText(String.format("%.2f", tempTo.getValue()));
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please Enter numbers onley...", "Error", JOptionPane.ERROR_MESSAGE);
                txtfldTempFrom.setText("");
                txtfldTempTo.setText("");
                lbelResult.setText("");
            }
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbelResult;
    private javax.swing.JList<TemperatureUnit> lstTempFrom;
    private javax.swing.JList<TemperatureUnit> lstTempTo;
    private javax.swing.JTextField txtfldTempFrom;
    private javax.swing.JTextField txtfldTempTo;
    // End of variables declaration//GEN-END:variables
}
